flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- brick-0.20
- word-wrap-0.1
- data-clist-0.1.1.0
- text-zipper-0.10
- vty-5.15
- haskell-src-exts-1.19.0
- hledger-lib-1.3
resolver: lts-8.19
